import type { Valor } from "../types/about";


export const VALORES: Valor[] = [
  { id: 'amor',             name: 'Amor',             description: 'Nuestro principio rector. Cada actividad nace del amor genuino hacia las personas y sus familias.',                                               imageUrl: '/img/fotos_valores/amor.jpg',            imageAlt: 'Personas tomadas de la mano en señal de unión' },
  { id: 'respeto',          name: 'Respeto',          description: 'Valoramos a cada persona como es, escuchando con atención y sin juzgar.',                                                                        imageUrl: '/img/fotos_valores/respeto.heic',        imageAlt: 'Personas de distintas generaciones conversando con atención' },
  { id: 'honradez',         name: 'Honradez',         description: 'Actuamos con transparencia y coherencia en cada decisión y compromiso.',                                                                          imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&q=80', imageAlt: 'Apretón de manos firme entre dos personas' },
  { id: 'paz',              name: 'Paz',              description: 'Promovemos ambientes de diálogo y armonía donde cada persona puede crecer.',                                                                      imageUrl: '/img/fotos_valores/paz.jpg',             imageAlt: 'Paisaje sereno al amanecer con cielo claro' },
  { id: 'honor',            name: 'Honor',            description: 'Reconocemos la dignidad de cada persona y la integridad de nuestra misión.',                                                                     imageUrl: '/img/fotos_valores/honor.jpg',           imageAlt: 'Persona mayor siendo reconocida con dignidad por su comunidad' },
  { id: 'lealtad',          name: 'Lealtad',          description: 'Permanecemos junto a nuestra comunidad en los momentos difíciles y en los de celebración.',                                                      imageUrl: '/img/fotos_valores/lealtad.jpg',         imageAlt: 'Grupo de personas caminando juntas' },
  { id: 'confianza',        name: 'Confianza',        description: 'Construimos relaciones sólidas basadas en la palabra cumplida y el compromiso real.',                                                            imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=600&q=80', imageAlt: 'Mano extendida en señal de apoyo y confianza' },
  { id: 'integridad',       name: 'Integridad',       description: 'Hacemos lo correcto incluso cuando nadie observa. Es el cimiento de todo lo que realizamos.',                                                   imageUrl: '/img/fotos_valores/integridad.jpg',      imageAlt: 'Persona trabajando con concentración y determinación' },
  { id: 'compromiso',       name: 'Compromiso',       description: 'Nos involucramos de lleno en cada proyecto, porque sabemos que el servicio verdadero cuesta.',                                                  imageUrl: '/img/fotos_valores/compromiso.jpg',      imageAlt: 'Voluntarios trabajando juntos en un proyecto comunitario' },
  { id: 'tolerancia',       name: 'Tolerancia',       description: 'Celebramos las diferencias como una riqueza y hacemos espacio para todas las historias.',                                                        imageUrl: '/img/fotos_valores/tolerancia_1.jpg',    imageAlt: 'Personas de distintos orígenes sentadas juntas en conversación' },
  { id: 'responsabilidad',  name: 'Responsabilidad',  description: 'Asumimos las consecuencias de nuestras acciones y cuidamos los recursos que nos son confiados.',                                                imageUrl: '/img/fotos_valores/responsabilidad.jpg', imageAlt: 'Persona liderando una tarea con cuidado y atención' },
  { id: 'bondad',           name: 'Bondad',           description: 'Elegimos la generosidad como forma de vida, sin esperar nada a cambio.',                                                                         imageUrl: '/img/fotos_valores/bondad.jpg',          imageAlt: 'Persona entregando comida con generosidad y calidez' },
  { id: 'solidaridad',      name: 'Solidaridad',      description: 'Nos ponemos del lado de quien más necesita, porque ninguna persona debería enfrentar sola sus desafíos.',                                       imageUrl: '/img/fotos_valores/solidaridad.webp',    imageAlt: 'Muchas manos superpuestas en señal de unión y solidaridad' },
  { id: 'esfuerzo',         name: 'Esfuerzo',         description: 'Damos lo mejor en cada tarea porque honrar a Dios y a nuestra comunidad merece lo máximo.',                                                    imageUrl: '/img/fotos_valores/esfuerzo.jpg',        imageAlt: 'Persona en plena actividad con determinación y esfuerzo' },
];